// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BridgeConfig dco_decode_bridge_config(dynamic raw);

  @protected
  BridgeSyncResult dco_decode_bridge_sync_result(dynamic raw);

  @protected
  BridgeTask dco_decode_bridge_task(dynamic raw);

  @protected
  BridgeTaskList dco_decode_bridge_task_list(dynamic raw);

  @protected
  BridgeWorkspace dco_decode_bridge_workspace(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BridgeTask> dco_decode_list_bridge_task(dynamic raw);

  @protected
  List<BridgeTaskList> dco_decode_list_bridge_task_list(dynamic raw);

  @protected
  List<BridgeWorkspace> dco_decode_list_bridge_workspace(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BridgeConfig sse_decode_bridge_config(SseDeserializer deserializer);

  @protected
  BridgeSyncResult sse_decode_bridge_sync_result(SseDeserializer deserializer);

  @protected
  BridgeTask sse_decode_bridge_task(SseDeserializer deserializer);

  @protected
  BridgeTaskList sse_decode_bridge_task_list(SseDeserializer deserializer);

  @protected
  BridgeWorkspace sse_decode_bridge_workspace(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BridgeTask> sse_decode_list_bridge_task(SseDeserializer deserializer);

  @protected
  List<BridgeTaskList> sse_decode_list_bridge_task_list(
      SseDeserializer deserializer);

  @protected
  List<BridgeWorkspace> sse_decode_list_bridge_workspace(
      SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_config(BridgeConfig self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_sync_result(
      BridgeSyncResult self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_task(BridgeTask self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_task_list(
      BridgeTaskList self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_workspace(
      BridgeWorkspace self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_task(
      List<BridgeTask> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_task_list(
      List<BridgeTaskList> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_workspace(
      List<BridgeWorkspace> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
