// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1505334582;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'bevy_tasks_flutter_bridge',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiAddWorkspace(
      {required String name, required String path});

  Future<BridgeTaskList> crateApiCreateList({required String name});

  Future<BridgeTask> crateApiCreateTask(
      {required String listId, required String title});

  Future<void> crateApiDeleteList({required String listId});

  Future<void> crateApiDeleteTask(
      {required String listId, required String taskId});

  Future<BridgeConfig> crateApiGetConfig();

  Future<List<BridgeTaskList>> crateApiGetLists();

  Future<BridgeConfig> crateApiInitApp();

  Future<List<BridgeTask>> crateApiListTasks({required String listId});

  Future<void> crateApiRemoveWorkspace({required String name});

  Future<void> crateApiReorderTask(
      {required String listId,
      required String taskId,
      required BigInt newPosition});

  Future<void> crateApiSetCurrentWorkspace({required String name});

  Future<void> crateApiSetWebdavConfig(
      {required String workspaceName, required String webdavUrl});

  Future<void> crateApiStoreWebdavCredentials(
      {required String domain,
      required String username,
      required String password});

  Future<BridgeSyncResult> crateApiSyncWorkspaceBridge(
      {required String workspacePath,
      required String webdavUrl,
      required String username,
      required String password});

  Future<BridgeTask> crateApiToggleTask(
      {required String listId, required String taskId});

  Future<void> crateApiUpdateTask(
      {required String listId,
      required String taskId,
      required String title,
      required String description});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiAddWorkspace(
      {required String name, required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAddWorkspaceConstMeta,
      argValues: [name, path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAddWorkspaceConstMeta => const TaskConstMeta(
        debugName: "add_workspace",
        argNames: ["name", "path"],
      );

  @override
  Future<BridgeTaskList> crateApiCreateList({required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bridge_task_list,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCreateListConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCreateListConstMeta => const TaskConstMeta(
        debugName: "create_list",
        argNames: ["name"],
      );

  @override
  Future<BridgeTask> crateApiCreateTask(
      {required String listId, required String title}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(listId, serializer);
        sse_encode_String(title, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bridge_task,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCreateTaskConstMeta,
      argValues: [listId, title],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCreateTaskConstMeta => const TaskConstMeta(
        debugName: "create_task",
        argNames: ["listId", "title"],
      );

  @override
  Future<void> crateApiDeleteList({required String listId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(listId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDeleteListConstMeta,
      argValues: [listId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeleteListConstMeta => const TaskConstMeta(
        debugName: "delete_list",
        argNames: ["listId"],
      );

  @override
  Future<void> crateApiDeleteTask(
      {required String listId, required String taskId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(listId, serializer);
        sse_encode_String(taskId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDeleteTaskConstMeta,
      argValues: [listId, taskId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeleteTaskConstMeta => const TaskConstMeta(
        debugName: "delete_task",
        argNames: ["listId", "taskId"],
      );

  @override
  Future<BridgeConfig> crateApiGetConfig() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bridge_config,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetConfigConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetConfigConstMeta => const TaskConstMeta(
        debugName: "get_config",
        argNames: [],
      );

  @override
  Future<List<BridgeTaskList>> crateApiGetLists() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_bridge_task_list,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGetListsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetListsConstMeta => const TaskConstMeta(
        debugName: "get_lists",
        argNames: [],
      );

  @override
  Future<BridgeConfig> crateApiInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bridge_config,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Future<List<BridgeTask>> crateApiListTasks({required String listId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(listId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_bridge_task,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiListTasksConstMeta,
      argValues: [listId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiListTasksConstMeta => const TaskConstMeta(
        debugName: "list_tasks",
        argNames: ["listId"],
      );

  @override
  Future<void> crateApiRemoveWorkspace({required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiRemoveWorkspaceConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRemoveWorkspaceConstMeta => const TaskConstMeta(
        debugName: "remove_workspace",
        argNames: ["name"],
      );

  @override
  Future<void> crateApiReorderTask(
      {required String listId,
      required String taskId,
      required BigInt newPosition}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(listId, serializer);
        sse_encode_String(taskId, serializer);
        sse_encode_usize(newPosition, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiReorderTaskConstMeta,
      argValues: [listId, taskId, newPosition],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiReorderTaskConstMeta => const TaskConstMeta(
        debugName: "reorder_task",
        argNames: ["listId", "taskId", "newPosition"],
      );

  @override
  Future<void> crateApiSetCurrentWorkspace({required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSetCurrentWorkspaceConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSetCurrentWorkspaceConstMeta =>
      const TaskConstMeta(
        debugName: "set_current_workspace",
        argNames: ["name"],
      );

  @override
  Future<void> crateApiSetWebdavConfig(
      {required String workspaceName, required String webdavUrl}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(workspaceName, serializer);
        sse_encode_String(webdavUrl, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSetWebdavConfigConstMeta,
      argValues: [workspaceName, webdavUrl],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSetWebdavConfigConstMeta => const TaskConstMeta(
        debugName: "set_webdav_config",
        argNames: ["workspaceName", "webdavUrl"],
      );

  @override
  Future<void> crateApiStoreWebdavCredentials(
      {required String domain,
      required String username,
      required String password}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(domain, serializer);
        sse_encode_String(username, serializer);
        sse_encode_String(password, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiStoreWebdavCredentialsConstMeta,
      argValues: [domain, username, password],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStoreWebdavCredentialsConstMeta =>
      const TaskConstMeta(
        debugName: "store_webdav_credentials",
        argNames: ["domain", "username", "password"],
      );

  @override
  Future<BridgeSyncResult> crateApiSyncWorkspaceBridge(
      {required String workspacePath,
      required String webdavUrl,
      required String username,
      required String password}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(workspacePath, serializer);
        sse_encode_String(webdavUrl, serializer);
        sse_encode_String(username, serializer);
        sse_encode_String(password, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bridge_sync_result,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSyncWorkspaceBridgeConstMeta,
      argValues: [workspacePath, webdavUrl, username, password],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSyncWorkspaceBridgeConstMeta =>
      const TaskConstMeta(
        debugName: "sync_workspace_bridge",
        argNames: ["workspacePath", "webdavUrl", "username", "password"],
      );

  @override
  Future<BridgeTask> crateApiToggleTask(
      {required String listId, required String taskId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(listId, serializer);
        sse_encode_String(taskId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bridge_task,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiToggleTaskConstMeta,
      argValues: [listId, taskId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiToggleTaskConstMeta => const TaskConstMeta(
        debugName: "toggle_task",
        argNames: ["listId", "taskId"],
      );

  @override
  Future<void> crateApiUpdateTask(
      {required String listId,
      required String taskId,
      required String title,
      required String description}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(listId, serializer);
        sse_encode_String(taskId, serializer);
        sse_encode_String(title, serializer);
        sse_encode_String(description, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiUpdateTaskConstMeta,
      argValues: [listId, taskId, title, description],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiUpdateTaskConstMeta => const TaskConstMeta(
        debugName: "update_task",
        argNames: ["listId", "taskId", "title", "description"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BridgeConfig dco_decode_bridge_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgeConfig(
      workspaces: dco_decode_list_bridge_workspace(arr[0]),
      currentWorkspace: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  BridgeSyncResult dco_decode_bridge_sync_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return BridgeSyncResult(
      uploaded: dco_decode_u_32(arr[0]),
      downloaded: dco_decode_u_32(arr[1]),
      deletedLocal: dco_decode_u_32(arr[2]),
      deletedRemote: dco_decode_u_32(arr[3]),
      conflicts: dco_decode_u_32(arr[4]),
      errors: dco_decode_list_String(arr[5]),
    );
  }

  @protected
  BridgeTask dco_decode_bridge_task(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return BridgeTask(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      description: dco_decode_String(arr[2]),
      status: dco_decode_String(arr[3]),
      dueDate: dco_decode_opt_String(arr[4]),
      createdAt: dco_decode_String(arr[5]),
      updatedAt: dco_decode_String(arr[6]),
      parentId: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  BridgeTaskList dco_decode_bridge_task_list(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return BridgeTaskList(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      createdAt: dco_decode_String(arr[2]),
      updatedAt: dco_decode_String(arr[3]),
      groupByDueDate: dco_decode_bool(arr[4]),
    );
  }

  @protected
  BridgeWorkspace dco_decode_bridge_workspace(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BridgeWorkspace(
      name: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      webdavUrl: dco_decode_opt_String(arr[2]),
      lastSync: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<BridgeTask> dco_decode_list_bridge_task(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bridge_task).toList();
  }

  @protected
  List<BridgeTaskList> dco_decode_list_bridge_task_list(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bridge_task_list).toList();
  }

  @protected
  List<BridgeWorkspace> dco_decode_list_bridge_workspace(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bridge_workspace).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BridgeConfig sse_decode_bridge_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_workspaces = sse_decode_list_bridge_workspace(deserializer);
    var var_currentWorkspace = sse_decode_opt_String(deserializer);
    return BridgeConfig(
        workspaces: var_workspaces, currentWorkspace: var_currentWorkspace);
  }

  @protected
  BridgeSyncResult sse_decode_bridge_sync_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_uploaded = sse_decode_u_32(deserializer);
    var var_downloaded = sse_decode_u_32(deserializer);
    var var_deletedLocal = sse_decode_u_32(deserializer);
    var var_deletedRemote = sse_decode_u_32(deserializer);
    var var_conflicts = sse_decode_u_32(deserializer);
    var var_errors = sse_decode_list_String(deserializer);
    return BridgeSyncResult(
        uploaded: var_uploaded,
        downloaded: var_downloaded,
        deletedLocal: var_deletedLocal,
        deletedRemote: var_deletedRemote,
        conflicts: var_conflicts,
        errors: var_errors);
  }

  @protected
  BridgeTask sse_decode_bridge_task(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_dueDate = sse_decode_opt_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    var var_parentId = sse_decode_opt_String(deserializer);
    return BridgeTask(
        id: var_id,
        title: var_title,
        description: var_description,
        status: var_status,
        dueDate: var_dueDate,
        createdAt: var_createdAt,
        updatedAt: var_updatedAt,
        parentId: var_parentId);
  }

  @protected
  BridgeTaskList sse_decode_bridge_task_list(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    var var_groupByDueDate = sse_decode_bool(deserializer);
    return BridgeTaskList(
        id: var_id,
        title: var_title,
        createdAt: var_createdAt,
        updatedAt: var_updatedAt,
        groupByDueDate: var_groupByDueDate);
  }

  @protected
  BridgeWorkspace sse_decode_bridge_workspace(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_webdavUrl = sse_decode_opt_String(deserializer);
    var var_lastSync = sse_decode_opt_String(deserializer);
    return BridgeWorkspace(
        name: var_name,
        path: var_path,
        webdavUrl: var_webdavUrl,
        lastSync: var_lastSync);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<BridgeTask> sse_decode_list_bridge_task(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BridgeTask>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bridge_task(deserializer));
    }
    return ans_;
  }

  @protected
  List<BridgeTaskList> sse_decode_list_bridge_task_list(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BridgeTaskList>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bridge_task_list(deserializer));
    }
    return ans_;
  }

  @protected
  List<BridgeWorkspace> sse_decode_list_bridge_workspace(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BridgeWorkspace>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bridge_workspace(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_bridge_config(BridgeConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_bridge_workspace(self.workspaces, serializer);
    sse_encode_opt_String(self.currentWorkspace, serializer);
  }

  @protected
  void sse_encode_bridge_sync_result(
      BridgeSyncResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.uploaded, serializer);
    sse_encode_u_32(self.downloaded, serializer);
    sse_encode_u_32(self.deletedLocal, serializer);
    sse_encode_u_32(self.deletedRemote, serializer);
    sse_encode_u_32(self.conflicts, serializer);
    sse_encode_list_String(self.errors, serializer);
  }

  @protected
  void sse_encode_bridge_task(BridgeTask self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_opt_String(self.dueDate, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
    sse_encode_opt_String(self.parentId, serializer);
  }

  @protected
  void sse_encode_bridge_task_list(
      BridgeTaskList self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
    sse_encode_bool(self.groupByDueDate, serializer);
  }

  @protected
  void sse_encode_bridge_workspace(
      BridgeWorkspace self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_opt_String(self.webdavUrl, serializer);
    sse_encode_opt_String(self.lastSync, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bridge_task(
      List<BridgeTask> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bridge_task(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bridge_task_list(
      List<BridgeTaskList> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bridge_task_list(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bridge_workspace(
      List<BridgeWorkspace> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bridge_workspace(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
