// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppConfigDto dco_decode_app_config_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  TaskDto dco_decode_box_autoadd_task_dto(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TaskDto> dco_decode_list_task_dto(dynamic raw);

  @protected
  List<TaskListDto> dco_decode_list_task_list_dto(dynamic raw);

  @protected
  List<WorkspaceEntry> dco_decode_list_workspace_entry(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  TaskDto dco_decode_task_dto(dynamic raw);

  @protected
  TaskListDto dco_decode_task_list_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WorkspaceEntry dco_decode_workspace_entry(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppConfigDto sse_decode_app_config_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  TaskDto sse_decode_box_autoadd_task_dto(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TaskDto> sse_decode_list_task_dto(SseDeserializer deserializer);

  @protected
  List<TaskListDto> sse_decode_list_task_list_dto(SseDeserializer deserializer);

  @protected
  List<WorkspaceEntry> sse_decode_list_workspace_entry(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  TaskDto sse_decode_task_dto(SseDeserializer deserializer);

  @protected
  TaskListDto sse_decode_task_list_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WorkspaceEntry sse_decode_workspace_entry(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_config_dto(AppConfigDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_task_dto(TaskDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_task_dto(List<TaskDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_task_list_dto(
    List<TaskListDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_workspace_entry(
    List<WorkspaceEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_task_dto(TaskDto self, SseSerializer serializer);

  @protected
  void sse_encode_task_list_dto(TaskListDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_workspace_entry(
    WorkspaceEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
